services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=django_payments_mollie
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
